### ISSUE TITLE
Not working encoded strings from Open Routing Machine

### ISSUE THREAD

**Issue by josephkandi** [raphaelmor/Polyline#17]
I tried this string 
```
}gqefAridwgFrYEAhfA{@jDsAxBoBzBaDtB{iAX{c@EsU]uf@?_WR~@tPlTFfg@?jUNj|@eBtu@K?z]cAjLkDlJuFjGyG`IyCjIsAlM?|k@v@|dArQbv@k@jIpA?
```

and it didnt output the right coordinates. I did divide them by 10 and i got the right coordinates just before adding them to the CLLocationCoordinate2D array

**Comment by raphaelmor** [comment]
When I try the string with google's polyline decoder : https://developers.google.com/maps/documentation/utilities/polylineutility , it decodes to invalid GPS locations : (373.3211 , -1220.3076).
I guess it's an issue with the encoder, or ORM uses another algorithm.

**Comment by raphaelmor** [comment]
@josephkandi you can use `v1.1.0` to decode polylines from OSRM : 
```swift
// OSRM uses a 6 digit precision
let polyline = Polyline(encodedPolyline: "ak{hRak{hR", precision: 1e6)
// or 
let coordinates: [CLLocationCoordinate2D]? = decodePolyline("ak{hRak{hR", precision: 1e6)
```

**Comment by josephkandi** [comment]
Thanks
