### ISSUE TITLE
Add the framework to a Swift Cocoa project

### ISSUE THREAD

**Issue by SuperGuillaume** [raphaelmor/Polyline#22]
Hello there,

I'm trying to add the project to my cocoa project .
Here is my podfile : 
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'
pod 'Polyline', '~> 2.0'
use_frameworks! 
```

It works perfectly in the simulator but the project can't be launched on a real iPhone.
The "Polyline" framework is not found. What am I doing wrong ?  
I tried to add the framework manually too but it still does not work.

If you have advices it would be great :sunglasses:

**Comment by raphaelmor** [comment]
I just updated Polyline to v3.0.0. 
Can you check if it fixes your issue ?

**Comment by raphaelmor** [comment]
I made a test with an empty project and this podfile:

```
source 'https://github.com/CocoaPods/Specs.git'                                                                                                                                                                                                              
platform :ios, '8.1'                                                                                                                                                                                                                       pod 'Polyline', '~> 3.0'                                                                                                                                                                                                                       
use_frameworks!
 ```

and it builds and run fine on both simulator and device (iPhone 6, iOS9.1).

**Comment by SuperGuillaume** [comment]
I'll test it, thanks :D

**Comment by SuperGuillaume** [comment]
Hmmm this is working like a charm now even with Xcode 7.1 :) Thank you very much
