### ISSUE TITLE
Polyline is looking for a new maintainer 

### ISSUE THREAD

**Issue by raphaelmor** [raphaelmor/Polyline#25]
I won't have much time in the future to work on __Polyline__.
So I'm looking for someone who's willing to maintain it.

__Polyline__ is pretty much feature complete and working well.

I think the only thing necessary would be to be sure it still works on future releases of __Swift__.

If you're interested, contact me here or on twitter :)

**Comment by ts** [comment]
I might be able to pick this up. Give me a few days to poke around, but I've been plenty happy with it so far. Certainly the least I could do!

**Comment by raphaelmor** [comment]
That would be very kind ! keep me informed :)

**Comment by tomtaylor** [comment]
I use Polyline in a currently maintained project, so I'd be happy to make fixes as Swift changes.

**Comment by raphaelmor** [comment]
Thanks a lot Tom for the work you're doing ! 
Closing this issue :)

**Comment by tomtaylor** [comment]
No problem!
