### ISSUE TITLE
OS X compatibility

### ISSUE THREAD

**Issue by tmcw** [raphaelmor/Polyline#26]
Polyline's podspec currently lists ios as the only valid target: https://github.com/raphaelmor/Polyline/blob/master/Polyline.podspec#L62

Reading the code, it looks like OSX should be supportable as well - all of the dependencies are available on both platforms.

**Comment by 1ec5** [comment]
This is happening in #27.

**Comment by tomtaylor** [comment]
Thanks, all merged in #27.
