### ISSUE TITLE
v3.3.0 has not been released to CocoaPods

### ISSUE THREAD

**Issue by 1ec5** [raphaelmor/Polyline#33]
@tomtaylor, looks like CocoaPods is still stuck on v3.2.2:

```
[!] Unable to satisfy the following requirements:

- `Polyline (~> 3.3)` required by `Podfile`
```

Would you mind pushing v3.3.0 to CocoaPods? I’d like to upgrade MapboxDirections.swift to work with Xcode 8 GM (both Swift 2.3 and Swift 3).

/cc @superpeteblaze

**Comment by tomtaylor** [comment]
Yeah, I had a problem pushing to Cocoapods, because of [this bug](https://github.com/CocoaPods/Xcodeproj/pull/407). I haven't updated to the 1.1.0.rc.1 release, but dropping back to Xcode 7.3 has let me push it.
