### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by tomtaylor** [raphaelmor/Polyline#35]
I don't really know what this involves, but we should probably do it.

**Comment by superpeteblaze** [comment]
I hear you, and I have had the same thought with my own code, but not sure if the Swift PM is where it needs to be to make this worthwhile.

**Comment by tomtaylor** [comment]
I've not looked in depth, but I think it's pretty easy to support with a `Package.swift` file, so it's probably just worth doing.

**Comment by tanzeelrana** [comment]
Cannot load underlying module for 'Polyline'
