### ISSUE TITLE
Error updating Carthage

### ISSUE THREAD

**Issue by BoogieMAN2K** [raphaelmor/Polyline#41]
When running `carthage update` I'm having this error on the terminal 

A shell task (/usr/bin/xcrun xcodebuild -project /Users/VictorAlejandria/Developer/Projects/Viantti/Viantti/Carthage/Checkouts/Polyline/Polyline.xcodeproj -scheme PolylineTV -configuration Release -sdk appletvos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64 /Users/VictorAlejandria/Developer/Projects/Viantti/Viantti/Carthage/Checkouts/Polyline/Polyline/Polyline.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

Any help.

**Comment by 1ec5** [comment]
Fixed in #40.
