### ISSUE TITLE
Swift 4 - 

### ISSUE THREAD

**Issue by cyrilzakka** [raphaelmor/Polyline#45]
Hey, just wanted to let you know this doesn't compile on Swift 4 with the following issue: 
`Polyline.swift:334:29: 'subscript' is unavailable` for the following code: 
```encodedString = encodedString[encodedString.index(after: currentIndex)..<encodedString.endIndex]```
Apparently `substring` was obsoleted.

**Comment by Krillere** [comment]
Someone posted this on SO too, seems to be the exact code from Polyline in the question. https://stackoverflow.com/questions/46170666/subscript-is-unavailable-in-swift-4 and https://stackoverflow.com/questions/45580072/why-wont-substrings-work-in-swift-4-anymore

The fix seems to be:
```
encodedString = String.UnicodeScalarView(encodedString[encodedString.index(after: currentIndex)..<encodedString.endIndex])
```

**Comment by tomtaylor** [comment]
Released in v4.2.0.

**Comment by 1ec5** [comment]
Numbering the Swift 4 upgrade as v4.2.0 broke [MapboxDirections.swift](https://github.com/mapbox/MapboxDirections.swift/), which depends on `~> 4.1.1` and compiles against Swift 3, for users of CocoaPods or Carthage and Xcode 8.3:

https://github.com/mapbox/MapboxDirections.swift/blob/042840b4fa194c0e1f722a8ec61f256b8a57c36f/Cartfile#L1

Going forward, it’s probably a good idea to bump the major version for any Swift version upgrade.

/ref mapbox/MapboxDirections.swift#181

**Comment by tomtaylor** [comment]
@1ec5 apologies, you're right, I broke semver. Next time!
