### ISSUE TITLE
Polyline decoder is taking too much time.

### ISSUE THREAD

**Issue by anil291987** [raphaelmor/Polyline#77]
Hi,

It is taking more time to decode the encoded polyline.
i.e 1000 location took around 5 sec.
Is there anyway to reduce this time ?

**Comment by 1ec5** [comment]
Hi, would you be able to provide an example encoded polyline that takes too long?

**Comment by anil291987** [comment]
It is problem in encoding/decoding from my side. It is resolved. Hence closing it.
