### ISSUE TITLE
Polyline(encodedPolyline: encodedPolyline) slow

### ISSUE THREAD

**Issue by Yukidama** [raphaelmor/Polyline#8]
I have a problem with slow decoding with `Polyline(encodedPolyline: encodedPolyline)`. Even an encoded polyline for a route around 30km takes several seconds, and if I try with a longer route, it can take minutes, sometimes I have a feeling it get stuck. Encoding a polyline is very fast on the other hand.

Example of an encoded polyline that will take around 3-6 seconds to decode is this:

    mbmrIe{gnAdHiCVIm@{NEsDFgAHu@^{C`@sC@_As@eWEoBIw@?QDYd@oB@Uv@eDHOViAPwB@_ACUGQIcDYiIsA{a@EcB?iBD]JyBV}C@GJKDOv@k@DCJBJCHIDc@GUEIJaH?}EN{@Le@T_@`EdAdAJhB^P?LGJMNYf@{Bn@_Cp@yCj@oDJu@Lk@JY\\w@MOQUYcAKi@G{APsFNqI?SGkA@m@AUeKmUcKoZkGkQkCiIgCuJuAuEgDeNgEuRgIq[yEeQo@yCmBaK_@cAcDoNwDuRoCaOaDkP}A}GoAcFyAqFyAcFiCcIsC{Hep@}_B{N{^EMS{@_@mAeAiC{@gCk@uBs@qDi@kFIqAc@uEm@wCCKOi@GMmAuBaAmAeAs@a@Qy@Qa@CcBLeAZs@d@]\\aDzDYVaLhPgAjAaCrBs@bAcBrAqDbCaD`B{B|@}DpAyBb@mEh@qDLgCA_Ic@u{@gGqISiB?kGLoI`@stAbI{L`@oINuI@o`AQ_EB{CH{DPiIx@}Fz@cGpAgEfAkkAz_@_DnAiCnA}CbBoBjA}EpDoC~B}AxAgDnD}CtDcDpE}A|BiClEcDdGmB`EkAnC{BvFgDvJ_AbDkB`HaBxGeAbFw@xD_AtFky@neFCP_@fAo@dCq@tBa@v@o@`AqAbAuDjAYNUZIRQv@?h@AR}@fBsDv@}@@c@WkE{e@{AkOwCcRuLgq@sCwPs@eDi[g}@_Wmq@KUYv@sB`E{C|EUZWNs@VS?k@Me@W_@YUYe@_Aq@kBuLia@qAyDQ}@]_AeFmQ]y@kEcOuAaFy@aDeK}[}AaHyD}OcAaFcAmImBwN

**Comment by raphaelmor** [comment]
Thanks for opening an issue.
I checked and my performances are not as bad as yours.
I tested with the polyline provided in the issue (Short) and the one you sent me by mail (Long). 
Here are the results I have : 

**Average of 100 iterations**

**Short polyline (no-optimisation):**

- iPhone 4s (7.1)  : 0.40s
- iPhone 6 (8.1.1) : 0.10s

**Short polyline (optimisation fastest -O3 / -O):**

- iPhone 4s (7.1)  : 0.05s
- iPhone 6 (8.1.1) : 0.01s

**Long polyline (no-optimisation):**

- iPhone 4s (7.1)  : 1.44s
- iPhone 6 (8.1.1) : 0.34s

**Long polyline (optimisation fastest -O3 / -O):**

- iPhone 4s (7.1)  : 0.26s
- iPhone 6 (8.1.1) : 0.06s

I checked the Google Map ```GMSPath``` performances and they are about ~1000x faster. So I'll have a look into optimizing this.

**Comment by raphaelmor** [comment]
@Yukidama : I pushed an optimisation that should improve performances. Could you check the `optimisation` branch (c5ba73a) and tell me if it is ok with you ?

**Comment by raphaelmor** [comment]
just for info here are the performance gains on my iPhone 6 (average of 100 iterations) : 

**compiler optim level : LLVM -O0 Swift -Onone**

before optim : 0,340s
after optim    : 0,013s

**compiler optim level : LLVM -O3 Swift -O**

before optim : 0,064s
after optim    : 0,00039s

**compiler optim level : LLVM -Ofast Swift -Ounchecked**

before optim : 0,056s
after optim    : 0,00023s
